---
title: 예외처리
categories: [java]
comments: true
---

+ 에러 : 개발자가 조치 할 수 없는 오류   
+ 예외 : 개발자가 조치 할 수 있는 오류   
   

```java
		int[] val3 = new int[3];
		System.out.println(val3[3]);
```
문법상으로는 맞지만(?) 0,1,2가 아닌 3에 접근하려고 해서 틀린 코드   

```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at chapter1.Ex1.main(Ex1.java:12)
```
이클립스에선 틀렸다고 안뜨는데   
실행시켜보면 실행은 안됨

```java
		try {
			int[] val3 = new int[3];
			System.out.println(val3[3]);
			
			int result = val1 + val2;
			System.out.println(result);
		} catch (/*처리 할 예외명*/ ArrayIndexOutOfBoundsException e) {
			System.out.println("배열의 범위를 벗어났습니다.");
		}
 ```
 이럴땐 침착하게 읽어보고   
 에러 떴다고 알려주는곳을 이렇게 트라이문에 넣으면 예외처리가 된다고 한다,,   
 
 ```java
 		try {
			System.out.println(val1 / -- val2);
			
			int[] val3 = new int[3];
			System.out.println(val3[3]);
			
			int result = val1 + val2;
			System.out.println(result);
			
		} catch (/*처리 할 예외명*/ ArrayIndexOutOfBoundsException | ArithmeticException e) {
			System.out.println("예외가 발생했습니다.");
		}
```
예외 종류가 여러가지면 이렇게 |로 묶어도 된다
